### ISSUE TITLE
Swagger "Try it out" not working for url parameters (e.g. infected?compress)

### ISSUE THREAD

**Issue by Ordinateur-Hack** [StudentsAgainstCovid19/corona-aid-api#103]
When pressing the "Try it out" and after that the "Execute" for any endpoint in the [Swagger documentation](https://api.corona-aid-ka.de/swagger-ui/index.html) the server response says:

`TypeError: Failed to fetch`

![image](https://user-images.githubusercontent.com/37160523/86513903-35397900-be0e-11ea-8d22-c40c19ffe976.png)

**Comment by marcauberer** [comment]
This is probably a Swagger bug, but we're going to look after it.

**Comment by jatsqi** [comment]
I think the problem here is the inferred url. As you can see in the generated curl command, the url is not the url of our backend, it is the local IP of the docker container (172.18.0.30/24 in this case).

**Comment by jatsqi** [comment]
I have changed the proxy configuration. It should work now with the correct base url and with https as protocol.

**Comment by marcauberer** [comment]
I've tested this out for all the endpoints. There is another issue with the url parameters. `?` are encoded wrong for the curl request. I experienced this problem some time ago with my own API. Here the link to the Swagger issue: https://github.com/springfox/springfox/issues/3281
