### ISSUE TITLE
Coherent use of tag names

### ISSUE THREAD

**Issue by Ordinateur-Hack** [StudentsAgainstCovid19/corona-aid-api#105]
Consider this code fragment from `xslt_calculate_prio.xls`
```
<lastname>
    <xsl:value-of select="surname"/>
</lastname>
```
- We should avoid using different terms for the same thing. Let's stick to `firstname` and `lastname` for the sake of simplicity and easy understanding of the tags.
- Furthermore, in the realtime endpoint (sse), there's a tag named `firstnames`. Please change that to `firstname` without the `s` at the end.
- Please also examine the rest of the code for more of these types of redundancy.

**Comment by marcauberer** [comment]
We'll try to fix that asap ;)

**Comment by marcauberer** [comment]
I just checked our code and I have to withdraw my statement: We always use `forename` and `surname` in our code.
Also, the term `firstnames` is not existent in our code, so I assume that this is an XSLT issue as well.
Nevertheless, we'll watch out for inconsistencies in the future.
