### ISSUE TITLE
Symptoms endpoint URL

### ISSUE THREAD

**Issue by Ordinateur-Hack** [StudentsAgainstCovid19/corona-aid-api#106]
We can get all symptoms by calling the `/symptom` endpoint. Since we get *all* symptoms it would make sense to **change the endpoint URL to `/symptoms`** (note the `s`). This would also unify the wording in the Swagger documentation:

![image](https://user-images.githubusercontent.com/37160523/86515513-b2b6b680-be19-11ea-9b72-dd2259b06422.png)

**Comment by marcauberer** [comment]
@Ordinateur-Hack There is the convention to set all names to singular for endpoints, mappings as well as database tables. We currently have a few inconsistencies there, that we fix soon.
In this case, I would rather change `symptoms` to `symptom`. Will tackle it in my next commit ;)

**Comment by marcauberer** [comment]
Fixed. Issue will be closed automatically, when the pr gets merged
