### ISSUE TITLE
ER diagram not up-to-date

### ISSUE THREAD

**Issue by Ordinateur-Hack** [StudentsAgainstCovid19/corona-aid-api#108]
The ER diagram is not up-to-date. The `history_item` still has a TODO in it and we don't have a `residental_group` implemented, right? Furthermore the cardinality `n` at `symptoms` is not correctly formatted.

![ER diagram](https://github.com/StudentsAgainstCovid19/corona-aid-api/blob/master/media/er_diagram.png?raw=true)

**Comment by marcauberer** [comment]
I opened a pr for this yesterday. You can approve and merge it if you want.

**Comment by Ordinateur-Hack** [comment]
Ok, I've merged it.

**Comment by marcauberer** [comment]
If you're wondering, why the image in the README did not change: The README link points to the master branch, so the change is only visible after merging to the master branch. We'll do that in the next continuous release.
