### ISSUE TITLE
Personalfeeling value of 10 in sample data

### ISSUE THREAD

**Issue by keksklauer4** [StudentsAgainstCovid19/corona-aid-api#116]
Seems as if your sample data generation is generating semantically incorrect data.

**Comment by marcauberer** [comment]
You you mean the daily generation of history items?

**Comment by keksklauer4** [comment]
I am not sure but probably yes.

**Comment by marcauberer** [comment]
What do you mean with semantically incorrect? Could you send me example xmls please?
