### ISSUE TITLE
Database column domains not suitable for real life data

### ISSUE THREAD

**Issue by jatsqi** [StudentsAgainstCovid19/corona-aid-api#15]
At the moment, postalCode and houseNumber in our infected table are Integers.
In real-life, postalCodes can have a trailing zero or can consist of multiple parts (e.g. 04564).
Housenumbers can also have letters at the end (e.g. 201a).

Solution: Use Strings / VARCHARSin our database, but with a fixed length. We dont need the Hibernate default length of 255 for such data,

**Comment by marcauberer** [comment]
Thanks for fixing. Forgot about that
