### ISSUE TITLE
Add age column to our ER diagram

### ISSUE THREAD

**Issue by marcauberer** [StudentsAgainstCovid19/corona-aid-api#19]
@jatsqi you wanted to add the attribute "age", that you implemented in #17.
Btw: When your working on it, please move the "n" at the symptoms table a bit, so that its visible ;)

**Comment by jatsqi** [comment]
The age attribute is not stored in our database :)
I added the runtime calculation in the DTO so we dont have additional redundancy in our database.

**Comment by marcauberer** [comment]
Okay. You're right, my bad. Shall we note it somewhere or do you think the Swagger page is enough in terms of documentation?

**Comment by jatsqi** [comment]
I think the Swagger documentation is enough. I mean this documentation is the specification for our Rest-API, so it should be noted there.

**Comment by marcauberer** [comment]
Ok. Closing this
