### ISSUE TITLE
Unnecessary back reference in SymptomDto

### ISSUE THREAD

**Issue by jatsqi** [StudentsAgainstCovid19/corona-aid-api#20]
In this DTO we store a back reference to all the history items that are related to a specific symptom.
At the moment I cannot image a practical use case for this, what do you think?
The only real use case for me are statistical evaluations, but this beyond the scope of this project.
The mapping for this attribute is missing too.

**Comment by marcauberer** [comment]
The back references are a holdover of the try to implement the model to DTO an vice versa with the ModelMapper.
We should delete the attributes everywhere they occur, cause they're not going to be included in the actual output anyways (don't forget the ManagedReference annotations on the other side of the relation).
