### ISSUE TITLE
Error when posting a history item with no symptoms.

### ISSUE THREAD

**Issue by keksklauer4** [StudentsAgainstCovid19/corona-aid-api#38]
Works with a symptom inserted, but with empty tag, it won't work.

**Comment by keksklauer4** [comment]
Btw I would highly appreciate if you could check the correctness of some examples in the API description. There is no example for a symptom which is the reason I could not post with symptoms yet.

**Comment by marcauberer** [comment]
> Works with a symptom inserted, but with empty tag, it won't work.

Could you send us the xml request, which you are trying to send? So we can better analyse what the problem is.

**Comment by marcauberer** [comment]
> Btw I would highly appreciate if you could check the correctness of some examples in the API description. There is no example for a symptom which is the reason I could not post with symptoms yet.

We know about that an will fix the API descriptions asap. Stay tuned ;)

**Comment by keksklauer4** [comment]
The following does not work (Error Code 400):
<History><infectedId>1</infectedId><notes></notes><personalFeeling>0</personalFeeling><status>0</status><symptom></symptom><timestamp>1591956934066</timestamp></History>

Whereas this works:
<History><infectedId>1</infectedId><notes></notes><personalFeeling>0</personalFeeling><status>0</status><symptom><symptom>2</symptom></symptom><timestamp>1591957036130</timestamp></History>

Note that even though i post a symptom, it is ignored. That probably is another error (or I used the wrong tag). JoJo told me to do so

**Comment by marcauberer** [comment]
I think the XML tags are case-sensitive. Please try `<Symptom>` instead of `<symptom>`

**Comment by marcauberer** [comment]
Your first issue is fixed. You now can provide a HistoryItem with no symptoms by writing `<symptoms/>` (Caution: I renamed the attribute from `symptom` to `symptoms`).
The changes are getting applied with the next merge to master branch.
Working now on the issue, that symptoms are not getting saved.

**Comment by jatsqi** [comment]
Symptoms are now saved correctly.

**Comment by marcauberer** [comment]
Merged now to master. You can start testing.

**Comment by keksklauer4** [comment]
Works perfectly fine now. Awesome!

**Comment by jatsqi** [comment]
You´re welcome
